version: '2'

networks:
  fabric_ov:
    external:
      name: fabric_ov

services:

  orderer0.example.com:
    image: hyperledger/fabric-orderer
    environment: 
      - GODEBUG=netdns=go
      - ORDERER_GENERAL_LOGLEVEL=ERROR
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/orderer.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg
      - ORDERER_GENERAL_LOCALMSPDIR=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes: 
      - /opt/go/src/github.com/hyperledger/fabric-test/fabric/common/tools/cryptogen/crypto-config:/opt/hyperledger/fabric/msp/crypto-config
    ports: 
      - 5005:7050
    container_name: orderer0.example.com
    networks:
      - fabric_ov
    # links:
    #   - "orderer0.example.com:orderer0.example.com"
    #   - "orderer1.example.com:orderer1.example.com"
    #   - "orderer2.example.com:orderer2.example.com"
    #   - "peer0.org1.example.com:peer0.org1.example.com"
    #   - "peer1.org1.example.com:peer1.org1.example.com"
    #   - "peer0.org2.example.com:peer0.org2.example.com"
    #   - "peer1.org2.example.com:peer1.org2.example.com"

  orderer1.example.com:
    image: hyperledger/fabric-orderer
    environment: 
      - GODEBUG=netdns=go
      - ORDERER_GENERAL_LOGLEVEL=ERROR
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/orderer.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg
      - ORDERER_GENERAL_LOCALMSPDIR=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes: 
      - /opt/go/src/github.com/hyperledger/fabric-test/fabric/common/tools/cryptogen/crypto-config:/opt/hyperledger/fabric/msp/crypto-config
    ports: 
      - 5006:7050
    container_name: orderer1.example.com
    networks:
      - fabric_ov
    # links:
    #   - "orderer0.example.com:orderer0.example.com"
    #   - "orderer1.example.com:orderer1.example.com"
    #   - "orderer2.example.com:orderer2.example.com"
    #   - "peer0.org1.example.com:peer0.org1.example.com"
    #   - "peer1.org1.example.com:peer1.org1.example.com"
    #   - "peer0.org2.example.com:peer0.org2.example.com"
    #   - "peer1.org2.example.com:peer1.org2.example.com"

  orderer2.example.com:
    image: hyperledger/fabric-orderer
    environment: 
      - GODEBUG=netdns=go
      - ORDERER_GENERAL_LOGLEVEL=ERROR
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/orderer.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg
      - ORDERER_GENERAL_LOCALMSPDIR=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/opt/hyperledger/fabric/msp/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes: 
      - /opt/go/src/github.com/hyperledger/fabric-test/fabric/common/tools/cryptogen/crypto-config:/opt/hyperledger/fabric/msp/crypto-config
    ports: 
      - 5007:7050
    container_name: orderer2.example.com
    networks:
      - fabric_ov
    # links:
    #   - "orderer0.example.com:orderer0.example.com"
    #   - "orderer1.example.com:orderer1.example.com"
    #   - "orderer2.example.com:orderer2.example.com"
    #   - "peer0.org1.example.com:peer0.org1.example.com"
    #   - "peer1.org1.example.com:peer1.org1.example.com"
    #   - "peer0.org2.example.com:peer0.org2.example.com"
    #   - "peer1.org2.example.com:peer1.org2.example.com"

  
      